services:
  application:
    image: 'homebank-app'
    container_name: app-homebank
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db/homebank
      SPRING_DATASOURCE_USERNAME: radu_baciu
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  #    depends_on: db
  db:
    image: mysql
    container_name: homebank
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: radu_baciu
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: homebank

